### ISSUE TITLE
Overhaul testing

### ISSUE THREAD

**Issue by v411e** [wegenerbenjamin/sepsesam#13]
Check if tests are "best practice" and if they can be enhanced in some way.

These functions are important for us:
#### Managing backup tasks
- [x] `backup_task_get`
      https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L842
- [x] `backup_task_create`
      https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L873
- [x] `backup_task_delete`
      https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L909

#### Managing clients
- [x] `client_find`
      https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L242
- [x] `client_create`
      https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L283
- [x] `client_update`
      https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L301
- [x] `client_delete`
      https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L324

#### Manage external groups
- [x] `external_group_find`
      https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L1510
- [x] `external_group_create`
      https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L1516
- [x] `external_group_delete`
      https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L1539

#### Manage groups
- [x] `group_create`
      https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L1347
- [x] `group_delete`
      https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L1372

#### Manage locations
- [x] `location_resolve_to_id`
      https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L444
- [x] `location_create`
      https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L388
- [x] `location_delete`
      https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L429

#### Manage commands
- [x] https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L1701

#### Manage command events
- [x] https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L1773

#### Manage backup schedules
- [x] https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L1630

#### Manage drive groups
- [x] https://github.com/SAPUCC/sepsesam/blob/6f1c3eb35f155f30b6c935d4bb60cf3706e5328a/src/sepsesam/api.py#L1845

**Comment by DerYannis1** [comment]
I'm finished with writing and checking of the marked tests. I've overhauled the api-wrapper a little bit and updated the functions used in "Manage groups" and will update the functions regarding "Manage external groups" to the api/v2 version.

**Comment by v411e** [comment]
Thanks a lot, feel free to open a PR whenever you are ready :)
